#!/bin/bash

if [ $# -eq 0 ]; then
  cd sitewiki
  pages=$(find *.md | sed -e 's/\.md$//')
  cd ..
else 
  pages=$1
fi

for page in $pages;
do
  echo "Converting: $page"
  head -17 docs/static/template > "docs/$page.html"
  pandoc --lua-filter=links-to-html.lua "sitewiki/$page.md" >> "docs/$page.html"
  tail -3 docs/static/template >> "docs/$page.html"
  tidy -iqm -w 80 --tidy-mark no "docs/$page.html"
done
