#!/usr/bin/env python3
import http.server, os, sys

class Handler(http.server.SimpleHTTPRequestHandler):
    def do_GET(self):
        path = self.translate_path(self.path)
        if not os.path.exists(path) and os.path.exists(path + '.html'):
            self.path += '.html'
        super().do_GET()

os.chdir(os.path.join(os.path.dirname(__file__), '..', 'docs'))
http.server.HTTPServer(('', 8000), Handler).serve_forever()
